### ISSUE TITLE
API suggestion: `WorkerPromise`

### ISSUE THREAD

**Issue by oberhamsi** [calvinmetcalf/catiline#105]
currently, the quickest way to put some data and a function into another eventloop is:

```
var worker = cw(myFunc)
var response = worker.data(YOUR DATA);
```

succincter and imo clearer:

```
var wp = new WorkerPromise(myFunc, myMessage);
wp.then(success)
```

**Comment by calvinmetcalf** [comment]
So that used to be a feature but I took it out because the actual creation of a worker [takes a non-trivial amount of time](http://jsperf.com/parall-threads/10).  There is [a plugin](https://github.com/calvinmetcalf/cw.single) I wrote to get that functionality allowing you to write with it handling the creation and closing of the worker

``` javascript
cw.single(func,data).then(success);
```

also shortest way to do it is

``` javascript
var worker = cw(myFunc);
worker.data(YOUR DATA).then(success);
```

though if your literally want to put some data and a function into another event loop you can write

``` javascript
cw.setImmediate(function(){
    yourFunc(yourData);
});
```

or

``` javascript
cw.resolve(function(){
    yourFunc(yourData);
}).then(success);
```

I may have to document better the setImmediate and promise methods that are used internally and exposed.

**Comment by oberhamsi** [comment]
Interesting, but I get 100 ops/sec for spawning new workers which would be plenty fast.

Does cw.setImmediate() spawn a worker or use one from an internal queue? I really don't like the setImmediate API and it doesn't look like this will become standard.

**Comment by calvinmetcalf** [comment]
cw.setImmediate() is literally just for putting things into the next event loop, no workers involved whatsoever, it's used internally to create promises and based on [this library](https://github.com/NobleJS/setImmediate) with all the fall backs for browsers that don't support web workers removed.

If you just need a simpler syntax for one off workers [you can use this plugin](https://github.com/calvinmetcalf/cw.single). which allows you to do `cw.single(func,data).then(success)` and it behind the scenes creates and terminates the worker.

**Comment by oberhamsi** [comment]
Okay right, I meant "in a _different_ event loop" (aka worker) not just later in the same event loop.

i'll try `single()`

**Comment by calvinmetcalf** [comment]
Ah you meant it in the context of thread, yeah try `cw.single` though if you find yourself using it more then once your probably better off doing 

``` javascript
var worker = cw({func1:myFunc,func2:otherFunc});
worker.func1(data1).then(...)
worker.func2(data2).then(...)
```

instead of

``` javascript
cw.single(myFunc,data1).then(...)
cw.single(otherFunc,data2).then(...)
```
