### ISSUE TITLE
Suggestion: Cancelling specific long worker calls

### ISSUE THREAD

**Issue by shole** [calvinmetcalf/catiline#110]
I'm working on an interactive app where the user manipulates a lot of data on screen.
I have workers on the background, constantly reading that new data (in queue mode) and then displaying it in processed form.
This process can take several seconds and I often have to discard the processed data as outdated because the user changed something.
With an enthusiastic user, the queue is soon filled up with calls and the app is on it's knees.
I can not cancel the entire queue because I may have several independent callers.
It would be useful here if I could assign a handler for specific queue calls and cancel or terminate those calls when they are no longer up to date.

**Comment by calvinmetcalf** [comment]
so to be able to reject a promise and if it's still in the queue pop it out so that we don't waste time in the worker?

**Comment by shole** [comment]
Yes, to pop it if it is still in the queue, and the option to reset the worker if it got that far.
Any data returned by the worker would be outdated, and with large datasets returning that data from the worker would also add to the waste.
Perhaps this could be like handle.cancel(); which removes from queue or tells worker to set cancel flag and not return a value.
And a nuclear option for larger worker tasks where appropriate, handle.cancel(true); which if already in a worker, would terminate the worker and replace with new worker from same init object.

**Comment by calvinmetcalf** [comment]
I'm thinking add a `cancel` method to the promise that if called when it's still in the queue rejects the promise and pops it out of the queue.  If it's already been sent to the worker the promise is still rejected and the data is just discarded when it gets sent back (canceling it in the worker isn't going to work because it's not going to read the next message until after it's done with what it's doing, i.e. sent back the data you don't want it to send back).

**Comment by calvinmetcalf** [comment]
@shole how does #111 look?

**Comment by shole** [comment]
The promise cancel looks like a good start.
There is still wasted effort when it has already entered a worker, but this already gives me some breathing room, thanks.
I will probably experiment with shooting down the worker, if I still see it necessary.

**Comment by calvinmetcalf** [comment]
the only way your going to be able to stop it after it has entered the worker is to terminate the worker and then start a new one, in a lot of cases it's going to be less work for the program to just wait for the computation to finish as making a new worker takes a bit of time. It might be easier to focus on breaking up your tasks into smaller steps so that there is less wasted effort if you bail once it's in a worker.

**Comment by calvinmetcalf** [comment]
closing this one unless it's still a problem
